apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadzxdx9734-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadzxdx9734-tenant-component
    app.kubernetes.io/part-of: loadzxdx9734-tenant-app
  name: loadzxdx9734-tenant-component
  namespace: loadzxdx9734-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadzxdx9734-tenant-component
    weight: null
status: {}
